### ISSUE TITLE
do i  repeat what you did for dormroom for every other rro?(Coming from someone inexperienced with old rec room server stuff)

### ISSUE THREAD

**Issue by milly531** [CrypticBren/CrypticSource#1]
istg if this gets speechbubbled

**Comment by CrypticBren** [comment]
"this will only have the required things to get into the dorm room the rest you have to figure out or do yourself" please read the "README" next time thanks(and yes i am speechbubbling this)

**Comment by milly531** [comment]
nick gurrs

**Comment by milly531** [comment]
if you speech this you want to kiss a big oily buff man

**Comment by CrypticBren** [comment]
> if you speech this you want to kiss a big oily buff man

I already speechbubbled it way before you sent this lmao

**Comment by milly531** [comment]
then speech the oily men message then send it to astra

**Comment by CrypticBren** [comment]
nuh uh uh now shhhhhhh
