### ISSUE TITLE
this don work

### ISSUE THREAD

**Issue by WeedDrinker1351** [CrypticBren/CrypticSource#3]
i got the build i patch the build i launch server(nothing modified) and launch rec room and it doesnt work
it says
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\weed\Desktop\CrypticSource\bin\Debug\net8.0
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - - 0
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      Protocol: HTTP/1.1
      Method: GET
      Scheme: http
      PathBase:
      Path: /
      Connection: keep-alive
      Host: localhost:5000
      User-Agent: BestHTTP
      Accept-Encoding: gzip, identity
      TE: identity
      Content-Length: 0
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[2]
      Response:
      StatusCode: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - 404 0 - 165.2108ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET http://localhost:5000/, Response status code: 404

**Comment by CrypticBren** [comment]
You have to modify the server URL to have "/nameserver" at the end and not just "/" or whatever you have at the end of the URL

**Comment by WeedDrinker1351** [comment]
i cant tell if im being autistic or if im doing something wrong bcuz i changed the url to "http://localhost:5000/nameserver" and it says in the console now:
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\weed\Desktop\CrypticSource-main\bin\Debug\net8.0
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/nameserver - - 0
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      Protocol: HTTP/1.1
      Method: GET
      Scheme: http
      PathBase:
      Path: /nameserver
      Connection: keep-alive
      Host: localhost:5000
      User-Agent: BestHTTP
      Accept-Encoding: gzip, identity
      TE: identity
      Content-Length: 0
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'CrypticSource.Controllers.ApiController.NameServer (CrypticSource)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
      Route matched with {action = "NameServer", controller = "Api"}. Executing controller action with signature System.String NameServer() on controller CrypticSource.Controllers.ApiController (CrypticSource).
{"Room":{"RoomId":1,"Name":"^DormRoom","Description":"Your not private dorm","ImageName":"DormRoom.png","CreatorPlayerId":7928150,"State":0,"Accessibility":2,"SupportsLevelVoting":false,"IsAGRoom":true,"CloningAllowed":false,"SupportsScreens":true,"SupportsWalkVR":true,"SupportsTeleportVR":true},"Scenes":[{"RoomSceneId":1,"RoomId":1,"RoomSceneLocationId":"76d98498-60a1-430c-ab76-b54a29b7a163","Name":"DormRoom","IsSandbox":true,"DataBlobName":"","MaxPlayers":4,"CanMatchmakeInto":true,"DataModifiedAt":"2018-09-28T15:29:02.6204035-06:00"}],"CoOwners":[],"InvitedCoOwners":[],"Hosts":[],"InvitedHosts":[],"CheerCount":0,"FavoriteCount":0,"VisitCount":0,"Tags":[]}
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'System.String'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action CrypticSource.Controllers.ApiController.NameServer (CrypticSource) in 128.593ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'CrypticSource.Controllers.ApiController.NameServer (CrypticSource)'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[2]
      Response:
      StatusCode: 200
      Content-Type: text/plain; charset=utf-8
      Date: Tue, 12 Nov 2024 01:25:59 GMT
      Server: Kestrel
      Transfer-Encoding: chunked
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/nameserver - 200 - text/plain;+charset=utf-8 303.7054ms
(sorry if this is bugging you)

**Comment by WeedDrinker1351** [comment]
if it is unclear, i mean that it shows that in the console, then it says failed to connect to recnet(student)

**Comment by CrypticBren** [comment]
Did you make sure you are on build "September 27th 2018" or "September 29th 2018"?

**Comment by WeedDrinker1351** [comment]
i am sure i am on 29th(I will check lator)

**Comment by CrypticBren** [comment]
i just realized why it probably isn't working so basically go into "JsonClasses/NameServer.cs" in the project and change everything that has "http://localhost:7689" to "http://localhost:5000" and do not change the one with ""ws://localhost:7698"

**Comment by CrypticBren** [comment]
i will go ahead push out a little fix for that rq

**Comment by CrypticBren** [comment]
i pushed out the fix that should work so for now i am gonna close this issue if you continue to have issues involving that you can send another comment to reopen this issue if there are no more issues please do not reopen this thanks

**Comment by WeedDrinker1351** [comment]
it works, thanks
