### ISSUE TITLE
notifications busted

### ISSUE THREAD

**Issue by Dunkini** [CrypticBren/CrypticSource#4]
yeah why

**Comment by CrypticBren** [comment]
you most likely broke smtg because last time i checked it works and plus i can't help you just by you saying "notifications busted" that doesn't really give me any info

**Comment by CrypticBren** [comment]
since you have not responded i am going ahead and closing this issue unless u have a different issue do not make a issue thanks

**Comment by milly531** [comment]
this is only up to entering the dorm, everything else u do urself bru
