### ISSUE TITLE
fix yo server

### ISSUE THREAD

**Issue by Dunkini** [CrypticBren/CrypticSource#5]
failed to recnet after logging in

**Comment by Dunkini** [comment]
d
weed

**Comment by CrypticBren** [comment]
as i said in my reply to your other issue i can't help by you just saying "failed to recnet after logging in"

**Comment by CrypticBren** [comment]
since you have not responded i am going ahead and closing this issue unless u have a different issue do not make a issue thanks

**Comment by Dunkini** [comment]
![vChK6pTy3vN3KbYZ7UU7k3-1200-80](https://github.com/user-attachments/assets/68c42530-52b6-4216-8268-ed627d2f4a28)
@CrypticBren

**Comment by CrypticBren** [comment]
ah nice you are one of those people
